CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS productdb;
CREATE DATABASE IF NOT EXISTS orderdb;

GRANT ALL PRIVILEGES ON authdb.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON productdb.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON orderdb.* TO 'user'@'%';

FLUSH PRIVILEGES;
