kind: ConfigMap
apiVersion: v1

metadata:
  name: online-shop-config-map
  namespace: online-shop-ns

data:
  MYSQL_DATABASE: authdb
  MYSQL_USER: user
  init.sql: |
    CREATE DATABASE IF NOT EXISTS authdb;
    CREATE DATABASE IF NOT EXISTS productdb;
    CREATE DATABASE IF NOT EXISTS orderdb;
    GRANT ALL PRIVILEGES ON authdb.* TO 'user'@'%';
    GRANT ALL PRIVILEGES ON productdb.* TO 'user'@'%';
    GRANT ALL PRIVILEGES ON orderdb.* TO 'user'@'%';
    FLUSH PRIVILEGES;
