---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deploy
  namespace: online-shop-ns
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysql-deploy
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: DATABASE_URL
              value: mysql+pymysql://user:password@mysql:3306/authdb
            - name: JWT_SECRET_KEY
              value: super-secret-change-in-prod
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: online-shop-config-map
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: online-shop-config-map
                  key: MYSQL_USER
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: online-shop-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: online-shop-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
