kind: Deployment
apiVersion: apps/v1

metadata:
  name: order-deploy
  namespace: online-shop-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: order

  template:
    metadata:
      labels:
        app: order

    spec:
      containers:
        - name: order
          image: heyyprakhar1/e-commerce-site-project-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_URL
              value: "mysql+pymysql://user:password@mysql-svc.online-shop-ns.svc.cluster.local:3306/authdb"
            - name: JWT_SECRET_KEY
              value: "super-secret-change-in-prod"

