kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: chatbot-pvc
  namespace: online-shop-ns

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: chatbot
