name: DevSecOps Pipeline
on:
    push:
        branches: [main]

jobs:
    code-quality-scan:
        uses: ./.github/workflows/code_quality.yml

    dependency-scan:
        uses: ./.github/workflows/dependency_scan.yml

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml

    dockerfile-scan:
        uses: ./.github/workflows/dockerfile-scan.yml

    docker-build-push:
        needs:
            [code-quality-scan, dockerfile-scan, secrets-scan, dependency-scan]
        uses: ./.github/workflows/docker-build-push.yml
        with:
            docker-tag: ${{ github.sha }}
        secrets: inherit

    image-scan:
        needs: docker-build-push
        uses: ./.github/workflows/image-scan.yml
        with:
            docker-tag: ${{ github.sha }}
        secrets: inherit

    deploy-to-server:
        needs: image-scan
        uses: ./.github/workflows/deploy_to_server.yml
        with:
            docker-tag: ${{ github.sha }}
        secrets: inherit
