name: docker-build-push
on:
  workflow_call:
    inputs:
      docker-tag:
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true
      SERVER_SSH_KEY:
        required: true
      SERVER_SSH_USER:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-auth:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build & push
        uses: docker/build-push-action@v6
        with:
          context: ./services/auth-service
          push: true
          tags: |
            ${{ vars.DOCKER_USER }}/e-commerce-site-project-auth-service:latest
            ${{ vars.DOCKER_USER }}/e-commerce-site-project-auth-service:${{ inputs.docker-tag }}

  build-order:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build & push
        uses: docker/build-push-action@v6
        with:
          context: ./services/order-service
          push: true
          tags: |
            ${{ vars.DOCKER_USER }}/order-service:latest
            ${{ vars.DOCKER_USER }}/order-service:${{ github.sha }}

  build-product:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build & push
        uses: docker/build-push-action@v6
        with:
          context: ./services/product-service
          push: true
          tags: |
            ${{ vars.DOCKER_USER }}/product-service:latest
            ${{ vars.DOCKER_USER }}/product-service:${{ github.sha }}
