name: image-scan
on: workflow_dispatch

jobs:
    image-scan:
        runs-on: ubuntu-latest
        steps:
            - name: code-checkout
              uses: actions/checkout@v4
            - name: Docker login
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: pull auth-service image
              run: docker pull ${{ vars.DOCKER_USER}}/e-commerce-site-project-auth-service:v3

            - name: pull order-service image
              run: docker pull ${{ vars.DOCKER_USER}}/e-commerce-site-project-order-service:v3

            - name: pull product-service image
              run: docker pull ${{ vars.DOCKER_USER}}/e-commerce-site-project-product-service:v3

            - name: scan-auth-service
              uses: aquasecurity/trivy-action@0.35.0
              with:
                  image-ref: ${{ vars.DOCKER_USER }}/e-commerce-site-project-auth-service:v3
                  format: table
                  severity: CRITICAL,HIGH
                  exit-code: 1
                  ignore-unfixed: true
            - name: scan-order-service
              uses: aquasecurity/trivy-action@0.35.0
              with:
                  image-ref: ${{ vars.DOCKER_USER }}/e-commerce-site-project-order-service:v3
                  format: table
                  severity: CRITICAL,HIGH
                  exit-code: 1
                  ignore-unfixed: true

            - name: scan-product-service
              uses: aquasecurity/trivy-action@0.35.0
              with:
                  image-ref: ${{ vars.DOCKER_USER }}/e-commerce-site-project-product-service:v3
                  format: table
                  severity: CRITICAL,HIGH
                  exit-code: 1
                  ignore-unfixed: true
